<a href="https://colab.research.google.com/github/spycoder01/Numpy/blob/main/Numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.sort

In [4]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([53, 22, 19, 43,  6, 62, 14, 96, 57, 17, 43, 11, 60, 64, 81])

In [ ]:
np.sort(a) #sorting into accending order

np.sort(a)[::-1] #sorting into decending order

array([94, 91, 91, 87, 77, 63, 55, 42, 42, 40, 29, 27, 24, 19,  7])

For 2D Array

In [ ]:
b = np.random.randint(1,100,12).reshape(3,4)
b

array([[88, 27,  6, 19],
       [20, 38, 19, 62],
       [68, 76, 40, 55]])

In [ ]:
np.sort(b) # row wise sorting

array([[ 6, 19, 27, 88],
       [19, 20, 38, 62],
       [40, 55, 68, 76]])

In [ ]:
np.sort(b, axis = 0) # Column wise sorting

array([[20, 27,  6, 19],
       [68, 38, 19, 55],
       [88, 76, 40, 62]])

np.concatenate

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d)) # row wise concatenation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d), axis = 1) # column wise concatenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

In [ ]:
e = np.array([1,1,2,2,3,3,4,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 5, 6, 6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims -
with the help of np.expand_dims() method, we can get the expanded dimensions of an array.

In [ ]:
print(a)

[77 29 24 91 55 27  7 40 63 42 87 19 91 42 94]


In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a, axis = 0).shape

(1, 15)

np.where - To find the indices of elements which satisfy the given condition

In [ ]:
print(a)

[77 29 24 91 55 27  7 40 63 42 87 19 91 42 94]


In [ ]:
np.where(a>50)

(array([ 0,  3,  4,  8, 10, 12, 14]),)

replace all value > 50 with 0

In [ ]:
np.where(a>50,0,a)

array([ 0, 29, 24,  0,  0, 27,  7, 40,  0, 42,  0, 19,  0, 42,  0])

In [ ]:
#replace all even numbers with 0
np.where(a%2 == 0,0,a)

array([77, 29,  0, 91, 55, 27,  7,  0, 63,  0, 87, 19, 91,  0,  0])

np.argmax - The numpy.argmax() function returns indices of the max element of the array in a particular axis

In [5]:
x = np.random.randint(1,20,10)
print(x)
np.argmin(x)

[ 7  7  7  4 11  8  3 12  1 10]


np.int64(8)

np.cumsum

In [8]:
x
np.cumsum(x)

array([ 7, 14, 21, 25, 36, 44, 47, 59, 60, 70])

In [10]:
np.cumprod(x)

array([       7,       49,      343,     1372,    15092,   120736,
         362208,  4346496,  4346496, 43464960])

In [17]:
y = np.arange(12).reshape(3,4)
print(y)
np.cumsum(y, axis = 1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

np.percentile

In [25]:
print(x)
np.percentile(x,100)

[ 7  7  7  4 11  8  3 12  1 10]


np.float64(12.0)

np.histogram

In [31]:
np.histogram(x, bins=[0,5,10,15,20])

(array([3, 4, 3, 0]), array([ 0,  5, 10, 15, 20]))

np.corrcoef

In [35]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,2,3,4,5])
np.corrcoef(salary,experience)

array([[1.        , 0.76150962],
       [0.76150962, 1.        ]])

np.isin

In [56]:
z = np.arange(10)
print(z)
items = [3,6,7]
np.isin(z,items)

[0 1 2 3 4 5 6 7 8 9]


array([False, False, False,  True, False, False,  True,  True, False,
       False])

np.flip

In [57]:
print(z)
np.flip(z)

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
print(y)
np.flip(y, axis = 1) #axis = 1 -> row wise fliping

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

np.put

In [54]:
print(a)
np.put(a,[0,1],[530,220]) # Its permanentely changes the specific index with the given values.

array([530, 220,  19,  43,   6,  62,  14,  96,  57,  17,  43,  11,  60,
        64,  81])

In [55]:
# To delete the particular index value
np.delete(a,[0,1])

array([19, 43,  6, 62, 14, 96, 57, 17, 43, 11, 60, 64, 81])

Sets functions

In [58]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
print(m)
print(n)

[1 2 3 4 5]
[3 4 5 6 7]


In [60]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [61]:
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
np.setdiff1d(m,n)

array([1, 2])

In [64]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [68]:
np.in1d(m,1)

<ipython-input-68-4dde4c85d026>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

np.clip

In [71]:
print(a)
np.clip(a,a_min = 25, a_max = 75) #Clip the numbers between 25 and 75

[530 220  19  43   6  62  14  96  57  17  43  11  60  64  81]


array([75, 75, 25, 43, 25, 62, 25, 75, 57, 25, 43, 25, 60, 64, 75])